### ISSUE TITLE
As an user, I want an interface so that I can make selections and use the application

### ISSUE THREAD

**Issue by QuiGonSwag** [JoshVorick/CurriculAnalyzer#10]
### Tasks
- [ ] Search Functionality
- [ ] Basic list output of data
- [ ] Allow users to make selections on courses they have taken
- [ ] Create objects to be used in graph visualization
- [ ] Create graph visualization of data
- [ ] Allow user to navigate around graph
